version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        depends_on:
            - mysql
    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        container_name: laravel-nginx
        ports:
            - "8080:80"
        depends_on:
            - app
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    mysql:
        image: mysql:8.0
        container_name: mysql_local
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: condominiodb
            MYSQL_USER: admin
            MYSQL_PASSWORD: adminpass
        volumes:
            - mysql_data:/var/lib/mysql
        restart: always

volumes:
    mysql_data:
