services:
    app:
        image: saavedraphp/condominio-web:latest
        depends_on:
            - mysql
        volumes:
            - public-shared:/var/www/public
            - storage-shared:/var/www/storage/app/public
    nginx:
        image: nginx:latest
        container_name: laravel-nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - /etc/letsencrypt/live/transparencia360.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
            - /etc/letsencrypt/live/transparencia360.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
            - public-shared:/usr/share/nginx/html:ro
            - storage-shared:/usr/share/nginx/html/storage:ro
    mysql:
        image: mysql:8.0
        container_name: mysql_local
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: condominiodb
            MYSQL_USER: admin
            MYSQL_PASSWORD: adminpass
        volumes:
            - mysql_data:/var/lib/mysql
        restart: always

volumes:
    mysql_data:
    public-shared:
    storage-shared:

